# Generated by Django 3.0.5 on 2020-10-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='borntime',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
