# Generated by Django 3.0.5 on 2020-10-04 04:40

from django.db import migrations, models
import djongo.models.fields
import music.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumsWTracks',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('album_type', models.CharField(max_length=200)),
                ('artists', djongo.models.fields.ArrayField(model_container=music.models.Arts, model_form_class=music.models.ArtsForm)),
                ('images', djongo.models.fields.ArrayField(model_container=music.models.Image)),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=11)),
                ('release_date_precision', models.CharField(max_length=200)),
                ('total_tracks', models.IntegerField(default=0)),
                ('trackslist', djongo.models.fields.ArrayField(model_container=music.models.Tracks)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TracksWAlbum',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('artists', djongo.models.fields.ArrayField(model_container=music.models.Arts, model_form_class=music.models.ArtsForm)),
                ('youtube_urls', models.CharField(max_length=200)),
                ('youtube_mr', models.CharField(max_length=200)),
                ('duration_ms', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('track_number', models.IntegerField(default=0)),
                ('preview_url', models.CharField(max_length=200)),
                ('popularity', models.IntegerField(default=0)),
                ('cluster', models.IntegerField(default=0)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('album_type', models.CharField(max_length=200)),
                ('artists', djongo.models.fields.ArrayField(model_container=music.models.Arts)),
                ('images', djongo.models.fields.ArrayField(model_container=music.models.Image)),
                ('name', models.CharField(max_length=200)),
                ('release_date', models.CharField(max_length=11)),
                ('release_date_precision', models.CharField(max_length=200)),
                ('total_tracks', models.IntegerField(default=0)),
                ('tracks', djongo.models.fields.ArrayField(model_container=music.models.Trs)),
            ],
        ),
        migrations.CreateModel(
            name='Artists',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('followers', models.CharField(max_length=20)),
                ('genres', djongo.models.fields.ArrayField(model_container=music.models.Genre)),
                ('images', djongo.models.fields.ArrayField(model_container=music.models.Image)),
                ('name', models.CharField(max_length=200)),
                ('popularity', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tracks',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('artists', djongo.models.fields.ArrayField(model_container=music.models.Arts, model_form_class=music.models.ArtsForm)),
                ('youtube_urls', models.CharField(max_length=200)),
                ('youtube_mr', models.CharField(max_length=200)),
                ('duration_ms', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('track_number', models.IntegerField(default=0)),
                ('preview_url', models.CharField(max_length=200)),
                ('album_id', models.CharField(max_length=200)),
                ('popularity', models.IntegerField(default=0)),
                ('cluster', models.IntegerField(default=0)),
            ],
        ),
    ]
